version: '3.4'

services:
  cloudmark:
    image: cloudmark
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
       MYSQL_HOST: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: sql11508841
  db:
    image: mysql
    container_name: db 
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql11508841
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
